### PR TITLE
Add upload feature

### LINKED ISSUE #98: [ui] file upload
Hey @mrassili 

Till now, we have not been uploading files to the backend, we only used data which already was available on the database. The upload part is one of the most important ones, it needs to be reliable. You are free to use whatever library you want or you can roll your own, but it should support the following features:

- Drag & drop support
- Upload progress bar
- Chunked uploads (Large files can be uploaded in smaller chunks with browsers supporting the Blob API).

When the file gets selected in the browser, we calculate :
1. Its size first, if more than 64MB, we should notify the user the file size is too big (this is already implemented), but I would like to change the notification style to the one available in vue-admin under : `/components/notification`

2. If size is OK, we locally calculate its sha256 hash (this is already implemented), then, we issue a  **GET** to `api.saferwall.com/v1/files/<sha256>`, if file exists (status code 200), we redirect to the summary view of the hash.  Because the file exists, we do not need to upload it, we just fetch the JSON immediately and display as before, this way we don't waste bandwidth.

3. If the file does not exist, you need to make a **POST** request to the following endpoint: `api.saferwall.com/v1/files`, it is a multipart form upload, if the server returns status code 201, it means all went fine and we need to display a progress tracker similar to the one in vue-admin under: `/components/progress-tracker`:

- Step 1: Uploaded
- Step 2: Queued
- Step 3: Processing
- Step 4: Finished

When the file gets successfully uploaded, you can keep pulling the server by making a **GET** request to `api.saferwall.com/v1/files/<sha256>`, the JSON will contain a state variable to indicate the progress of the scan, called **status**. We might user socket io later to avoid this pulling.

<p align="center"> 
    
</p>

Thanks!

### PR DESCRIPTION
**Pull request by mrassili**
This is a WIP

fixes #98

### CODE REVIEW

**Comment by LordNoteworthy** [comment]
Amazing work! Thank you.

Get rid of all occurrences of `?api-key=secret` that we have in urls.

**Comment by mrassili** [comment]
`api-key` not required anymore?

**Comment by LordNoteworthy** [comment]
nope, as we now are using jwt for auth, and not api keys.

**Comment by mrassili** [comment]
Good, will delete it in the next commit

**Comment by mrassili** [comment]
@LordNoteworthy the `status` is always equal to `0` (Even after 15 minutes for a few bytes file.
What are the values that it should normally hold?

**Comment by LordNoteworthy** [comment]
Yeah, I know, will deploy that changs today. Maybe in 2h from now. Sorry.

**Comment by mrassili** [comment]
I think it's all good now!
A couple of things that need fixing:

- Pulling the JSON (e.g. in Summary) take too long for a very small file, we should think of a way to pull only a subset of data (as you suggested)

**Comment by LordNoteworthy** [comment]
Awesome !! I am merging this now.

**Pull request merged**
