### PR TITLE
Update login page desing and solve the login issue

### PR DESCRIPTION
**Pull request by LordNoteworthy**

### CODE REVIEW

**Comment by LordNoteworthy** [comment]
I tried the code, and it works. Thanks a lot.

One small question, when we return the response after a login with the set cookie, we already set an expiration for the token, do we need the one you have in your code ? @UqabSoft

**Comment by UqabSoft** [comment]
ok, In that case, it's not needed, I removed the cookie expiration time for token and push updates.

**Comment by LordNoteworthy** [comment]
Go you. Did you try to upload a file after that ? When you login and send a file to be scanned, it seems it is missing the token

**Comment by UqabSoft** [comment]
I did not try that, let me check it.

**Comment by LordNoteworthy** [comment]
Here is the workflow this happens when you try to upload a file:

https://github.com/saferwall/saferwall/issues/98

**Pull request merged**
