### PR TITLE
Request password reset

### PR DESCRIPTION
**Pull request by mrassili**
Design: 

form design

### CODE REVIEW

**Comment by mrassili** [comment]
I just removed a few unnecessary packages to optimize the build a bit.
Before:
```
bundle size: 207 KB
build time: 9400ms
```
Now: (17% decrease in bundle size & 30% in build time)
```
bundle size: 171 KB
build time: 5900ms
```
_which is pretty decent_

**Comment by LordNoteworthy** [comment]
You can also design a change password form where the user is asked to enter new credentials

Just two fields: New Password & repeat new password, performing the same validation as we had before for password + it should be ofc the same password between the two input fields.

**Comment by LordNoteworthy** [comment]
Can I merge this ?

**Comment by mrassili** [comment]
If you're done with the backend logic, I can finish it

**Comment by LordNoteworthy** [comment]
It is done and deployed from my side, few changes, just regarding the routes:


// handle user login (added the v1)
**e.POST("/v1/auth/login/**"
// to request a pwd reset, send a DELETE to /v1/users/password/, email in body
**e.DELETE("/v1/users/password/**"

// change password (what you will send from the form)
// when the user will click in the email, the token is located in the query string param, get it from there and send it to me + password (new) in body in json to:
**e.POST("/v1/users/password/"**

**Comment by mrassili** [comment]
@LordNoteworthy 
The link I get on the reset password email looks like this:
```
http://dev.api.saferwall.com:80/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwicHVycG9zZSI6InJlc2V0LXBhc3N3b3JkIiwiZXhwIjoxNTY2NjY3Njc3fQ.w5-3k9WUivolKBfbw5THXeIdqyjiTbY2mQnstYtzhYw
```
But it doesn't render anything
Can you render the reset form somehow?

**Comment by LordNoteworthy** [comment]
Yeah sorry, I will fix it, you can just  take the token from their, and act as you received it in your reset_password route, so you can continue  until I fix it.

**Comment by LordNoteworthy** [comment]
Take then token + new password, both in json, send that and look if pwd wad updated successfully

**Comment by mrassili** [comment]
> Yeah sorry, I will fix it, you can just take the token from their, and act as you received it in your reset_password route, so you can continue until I fix it.

The problem is, when the user accesses the link, it renders nothing but a json file with a `message` key. So I can't do anything on my end (no frontend), hope that makes sense

**Comment by mrassili** [comment]
@LordNoteworthy Password reset works now! You can merge this
_PS: The UI route is `reset_password` (not hyphen)_

**Comment by LordNoteworthy** [comment]
Awesome :) thank you for that !

2 gotchas:
- IMHO, hyphens are more suitable than underscore for URLs (for readability and SEO), check this: https://stackoverflow.com/questions/119312/urls-dash-vs-underscore
- Before you made the last commit. Maybe the issue is still their. I had issues when running `yarn dev`, something about `potentially fixable with the --fix` option`, you can always verify that if you run a docker container and try to build inside it. I did what was mentionned here with the fix: true and then it worked: https://stackoverflow.com/questions/54173375/potentially-fixable-with-the-fix-option

**Comment by mrassili** [comment]
You are 100% right, I'll switch to dash separated URLs. Did you fix it the eslint problem, try running `yarn lint`?

**Comment by LordNoteworthy** [comment]
I did, did not work. I will retry it today later..

**Comment by mrassili** [comment]
@LordNoteworthy run `yarn clean && yarn reinstall`
• Removed formatting errors from ESLint so they don't interfere with it
• Formatting can now be fixed w/ running `yarn prettify` (using `prettier`)

**Comment by mrassili** [comment]
Commits `c1332bb` and `862abd1` should fix #113

**Comment by LordNoteworthy** [comment]
Good job ! all fine now, thanks a lot ! merging it, yay ^^

**Comment by mrassili** [comment]
fixes #117

**Pull request merged**
