### PR TITLE
[ui] Design 404, 403 and 500 error pages

### PR DESCRIPTION
**Pull request by mrassili**
Let me know if there's anything you'd like to change!

PS: 403/500 aren't working yet, need to figure when to send them?

### CODE REVIEW

**Comment by mrassili** [comment]
Illustrations courtesy of unDraw.co

**Comment by LordNoteworthy** [comment]
Yeah! Seems what we are looking for :) though we have to keep the same color/theme of our UI. That green and orange, so UX is consistent.

**Comment by mrassili** [comment]
Fair enough! Working on it ;)

**Comment by mrassili** [comment]
Mobile


Desktop


How's that look, @LordNoteworthy?

**Pull request closed without merging**
