### PR TITLE
Basic login design and route protection

### LINKED ISSUE #97: [ui] Design a sign in/sign up page
Hello @mrassili 

We need to design a sign in / sign up page.

Sign up contains the following input fields

- email
- username
- password

Plus a checkbox about: I agree to the [terms and conditions](url)
Then a button to Submit.

Notes:
- We dont need a repeat password. 
- Fot the moment, let's enforce any 8 char length.
- Input should be highlighted by red/green depending on success. I will give you later how you can contact the backend to know if username/email are available. In this task, you can just check if email format is valid in client side.

Sign in contains the following fields
- email or username
- password

Not a member ? [Sign up](url)
Forgot [password ](url)?

Below is an example, the form should be placed in the center of the page, under our logo, also only the header (top navbar) and the footer should exist in the page, no left sidebar.

<p align="center"> 
    
</p>

Logo: https://github.com/saferwall/saferwall/blob/master/website/_assets/images/saferwall.png

You can check the dashboard I provided before, at the section forms, there are examples you can use.

Cheers,

### PR DESCRIPTION
**Pull request by mrassili**
fixes #97 

This is a WIP
I designed a simple login layout, no validation for now, just route protection for the upload feature

To do:

- Make a registration page and link it to backend
- Add validation checks
- Integrate jwt

Login page:
Screen Shot 2019-07-22 at 10 15 46 PM

### CODE REVIEW

**Comment by mrassili** [comment]
Screen Shot 2019-07-23 at 12 19 57 AM

**Comment by LordNoteworthy** [comment]
Awesome work !! Shall I merge ?

**Comment by mrassili** [comment]
Thanks Ayoub! Let's keep it open as I'd like to use it to keep track of tasks

**Comment by mrassili** [comment]
Enhanced styling and validation
Screen Shot 2019-07-23 at 10 14 59 PM

**Comment by LordNoteworthy** [comment]
Looks neat ! Thank you.

**Comment by LordNoteworthy** [comment]
@mrassili 

Additing to what mentionned before:
- Let's include a show password icon.
- For username, we should apply some more validation, a regex one like `[a-z0-9_-.]{3,20}$` but if you want to do it properly, check this [thread](https://stackoverflow.com/questions/1221985/how-to-validate-a-user-name-with-regex ) as we dont want also usernames to have only underscrores or hyphens.

1. To register a new account, send a **POST** request to `api.saferwall.com/auth/register`:
- it expects a username, password, and email, in success, it returns an HTTP status code 201.
- if email/username exists or invalid data passed like wrong email format, it returns HTTP status code 400 with a json in body which gives you more details about the error, the key in json is "*verbose_msg*".
- upon failure, we should alert the user with a notification.
- upon success, we should redirect to the login view and notify that email address needs to be verified.

2. To login, you need to issue a GET request to `api.saferwall.com/auth/login`

- it expects a username, password sent as a POST request.
- we should apply same validations we did for user registration for username and password.
- upon successful login, you will get a cookie which contains a jwt token, we use a cookie to store a token instead of localstorage for security reasons.

I did not implement my part in the backend yet, but prepares you to do something in client side.

**Comment by mrassili** [comment]
Okay so username validation as I see it is:

- usernames should have a length between 3 and 20
- usernames should start with a letter
- usernames should end with an alpha-numeric
- usernames can contain any of [a-z0-9\._-]
- numbers should not be in the vicinity of each other more than 4x (i.e. u1234 is a match, u12345 is not)
- each ., - and _ should be followed by an alpha-numeric

I wrote a function that tests against those rules, if that's fine let me know and I'll finalize the registration

**Comment by LordNoteworthy** [comment]
Seems good to me, 

* usernames can contain any of [a-z0-9._-]
Shouldn't we allow also A-Z ?

**Comment by mrassili** [comment]
Okay perfect!

**Comment by LordNoteworthy** [comment]
Ready to merge ? :)

**Comment by mrassili** [comment]
Yes @LordNoteworthy you can merge
(As the app gets larger, I might need to do some refactoring, but for now things are working as expected)

**Comment by LordNoteworthy** [comment]
Amazing ! Thanks a lot of your work.

**Pull request merged**
