### PR TITLE
[feature] Refactor storage names to support conditional config

### PR DESCRIPTION
**Pull request by RC1140**
Minor changes to support the conditional generation of the templates (either efs or nfs).

### CODE REVIEW

**Comment by LordNoteworthy** [comment]
That will effectively solve the problem regarding the `-` character.

However, because the `efs-provisioner`/`nfs-server-provisioner` named their chart name with the `-`:

image

We are forced to obey to their naming if we want to override the config like:

```yaml
nfs-server-provisioner:
  replicaCount: 2
```

We can still have it without the hyphen, but we would end up with two entries in the `values.yaml`.

I did some googling and figure out that we can get around that issue with:
``` yaml
{{- if index .Values "efs-provisioner" "enabled" }}
```

All in all, something like this should work as well:

```yaml
{{- if or (index .Values "efs-provisioner" "enabled") (index .Values "nfs-server-provisioner" "enabled") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "saferwall.fullname" . }}-samples
  {{- if index .Values "efs-provisioner" "enabled" }}
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
  {{- end }}
spec:
  {{- if index .Values "efs-provisioner" "enabled" }}
  storageClassName: aws-efs
  {{- else if index .Values "nfs-server-provisioner" "enabled" }}
  storageClassName: nfs
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
```

If that makes sense to you, I will wait for your commit.

**Comment by RC1140** [comment]
I didnt realize that the values automatically got overwritten when the names matched to import the settings. Let me test the changes you proposed , it seems like it could work.

**Comment by LordNoteworthy** [comment]
I pick up your changes in #227 , rebase them to master. Thanks a lot @RC1140

**Comment by RC1140** [comment]
Thanks

**Pull request closed without merging**
